version: "3.8"

networks:
  traefik:
    external: true
  vim-network:
    driver: bridge

services:
  server:
    image: vim-server:latest
    container_name: vim-server
    restart: unless-stopped
    networks:
      - traefik
      - vim-network
    environment:
      - GO_ENV=production
      - SERVER_PORT=8288
      - DB_PATH=/data/vim.db
      - DB_CACHE_ADDRESS=valkey
      - DB_CACHE_PORT=6379
      - DB_CACHE_RESET=-1
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - SECURITY_SALT=${SECURITY_SALT}
      - SECURITY_PEPPER=${SECURITY_PEPPER}
      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
    volumes:
      - vim_data:/data
    depends_on:
      - valkey
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8288/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    image: vim-client:latest
    container_name: vim-client
    restart: unless-stopped
    networks:
      - traefik
      - vim-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vim-client.rule=Host(`waugze.com`)"
      - "traefik.http.routers.vim-client.entrypoints=http,https"
      - "traefik.http.routers.vim-client.tls=true"
      - "traefik.http.routers.vim-client.tls.certresolver=letsencrypt"
      - "traefik.http.services.vim-client-service.loadbalancer.server.port=80"
    depends_on:
      - server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: vim-valkey
    restart: unless-stopped
    networks:
      - vim-network
    volumes:
      - valkey_data:/data
      - valkey_logs:/var/log/valkey
    environment:
      - VALKEY_ENV=production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

volumes:
  vim_data:
  valkey_data:
  valkey_logs:

